"""API schemas."""

from api.schemas.ai_hints import (
    AIErrorExplanation,
    AIErrorRequest,
    AIErrorResponse,
    AIHint,
    AIHintFeedback,
    AIHintRequest,
    AIHintResponse,
    AIReportRequest,
    CodeReviewRequest,
    CodeReviewResult,
)
from api.schemas.curriculum import (
    Curriculum,
    Day,
    Problem,
    Week,
)
from api.schemas.execution import (
    CodeExecutionRequest,
    CodeExecutionResponse,
    CodeValidationRequest,
    ExecutionResult,
    ProjectExecutionRequest,
    ProjectExecutionResponse,
    ProjectFile,
    ProjectFileValidation,
    ProjectMetadata,
    ProjectRunRequest,
    ProjectSaveRequest,
    ProjectSaveResponse,
    ProjectSubmissionResponse,
    ProjectTemplate,
    ProjectTemplateFile,
    ProjectTestRequest,
    ProjectTestResult,
    ProjectValidationResponse,
    ValidationResponse,
)
from api.schemas.progress import (
    Activity,
    ActivityCreate,
    ActivityList,
    ActivitySummary,
    ActivityType,
    Bookmark,
    BookmarkCheck,
    BookmarkCreate,
    BookmarkList,
    BookmarkUpdate,
    Draft,
    DraftCreate,
    DraftList,
    DraftUpdate,
    ItemType,
    ProblemStatus,
    Progress,
    ProgressCreate,
    ProgressList,
    ProgressStats,
    ProgressUpdate,
    WeekProgress,
)
from api.schemas.user import (
    MagicLinkRequest,
    MagicLinkVerify,
    TokenResponse,
    User,
    UserCreate,
    UserStats,
    UserUpdate,
)

# UserResponse is an alias for User
UserResponse = User
from api.schemas.verification import (
    ErrorCategory,
    HintSuggestion,
    TestResult,
    TestStatus,
    VerificationRequest,
    VerificationResponse,
    VerificationResult,
    VerificationSummary,
)

__all__ = [
    # AI Hints
    "AIErrorExplanation",
    "AIErrorRequest",
    "AIErrorResponse",
    "AIHint",
    "AIHintFeedback",
    "AIHintRequest",
    "AIHintResponse",
    "AIReportRequest",
    "CodeReviewRequest",
    "CodeReviewResult",
    # Curriculum
    "Curriculum",
    "Day",
    "Problem",
    "Week",
    # Execution
    "CodeExecutionRequest",
    "CodeExecutionResponse",
    "CodeValidationRequest",
    "ExecutionResult",
    "ProjectExecutionRequest",
    "ProjectExecutionResponse",
    "ProjectFile",
    "ProjectFileValidation",
    "ProjectMetadata",
    "ProjectRunRequest",
    "ProjectSaveRequest",
    "ProjectSaveResponse",
    "ProjectSubmissionResponse",
    "ProjectTemplate",
    "ProjectTemplateFile",
    "ProjectTestRequest",
    "ProjectTestResult",
    "ProjectValidationResponse",
    "ValidationResponse",
    # Progress & Tracking
    "Activity",
    "ActivityCreate",
    "ActivityList",
    "ActivitySummary",
    "ActivityType",
    "Bookmark",
    "BookmarkCheck",
    "BookmarkCreate",
    "BookmarkList",
    "BookmarkUpdate",
    "Draft",
    "DraftCreate",
    "DraftList",
    "DraftUpdate",
    "ItemType",
    "ProblemStatus",
    "Progress",
    "ProgressCreate",
    "ProgressList",
    "ProgressStats",
    "ProgressUpdate",
    "WeekProgress",
    # User
    "MagicLinkRequest",
    "MagicLinkVerify",
    "TokenResponse",
    "User",
    "UserCreate",
    "UserResponse",
    "UserStats",
    "UserUpdate",
    # Verification
    "ErrorCategory",
    "HintSuggestion",
    "TestResult",
    "TestStatus",
    "VerificationRequest",
    "VerificationResponse",
    "VerificationResult",
    "VerificationSummary",
]
